### ISSUE TITLE
I broke the log stats

### ISSUE THREAD

**Issue by dbrah** [abueide/harry-plotter#101]
I wanted to see the stats for my past plots created prior to downloading harry plotter, so I pasted all the log files from my .chia dir to the harry plotter  log directory - finished folder. I then hit 'load log stats' and here's what i got. There are only 145 log files in this directory, but it took off counting all sorts of plots. 
![image](https://user-images.githubusercontent.com/85514121/121065819-2f26e780-c797-11eb-9122-dfdd3c8caf17.png)

**Comment by abueide** [comment]
is this still happening in 1.1.14? also you can fix this by deleting your logs folder in ~/.harryplotter/plotlogs

**Comment by dbrah** [comment]
ah, I will check after this plot is finished. did not notice the new
version!

**Comment by abueide** [comment]
@dbrah you can upgrade while plots are running as long as you don't force stop

**Comment by dbrah** [comment]
So if I close the gui and reopen after update, the plots will still be
running?

**Comment by abueide** [comment]
yes

**Comment by dbrah** [comment]
Okay so the plot seems to have continued to run, which does make sense
considering it's running the chia script. but I only know this by looking
at the log file. When I reopen harry plotter again (now 1.1.4) it doesn't
show the active plot. on the job page. It shows the plot job that I
created, but the log window and other stats are blank. Is this expected
behavior? I'm going to try and move the previous log files over to see if i
get the same result as 1.1.13.

**Comment by dbrah** [comment]
Importing the logs worked this time! Kudos!

**Comment by abueide** [comment]
no it usually should still show the logs file and stats of currently running plots after reopening, but sometimes it can break the reattaching process between upgrades if the format changes. Sorry about that. If you have any other issues let me know.
