### ISSUE TITLE
Which threads are only used?

### ISSUE THREAD

**Issue by a19901201** [abueide/harry-plotter#102]
Do we have this feature? If there is no hope, it can increase!

**Comment by abueide** [comment]
I don't understand

**Comment by abueide** [comment]
@a19901201 affinity support probably won't be in 1.2 but will be one of the bigger features after.

For now there's a video showing how this guy set up harry plotter to use specific threads only
https://www.youtube.com/watch?v=CByz3VSESvI

**Comment by a19901201** [comment]
Well, thanks for your hard work, although this is very troublesome for my machine with 88 threads, but thank you.

**Comment by abueide** [comment]
haha yeah that would be a lot of trouble. I'll keep it in mind if I get enough funding to keep working on harry plotter after the big 1.2 release. It'll probably be one of the first features.

**Comment by a19901201** [comment]
Looking forward to your work, I will promote your program to the public and give you a cup of coffee!

**Comment by firipusan** [comment]
Cpu affinity would be a great addition. When you say "funding", how much funding are you looking for?

**Comment by abueide** [comment]
Just enough to pay rent and food for while I work on it (which is currently $900/mo). In 1.2 I'll add an option to be able to donate some plots and pooling support which will support me with revenue share on pool fees if you use the default pool.

After 1.2 is when I'll decide whether to keep working on it or to move on to my next chia project. Ofc, I'll keep fixing bugs.

**Comment by a19901201** [comment]
Develop a farming program that can be used in the official POOL, which also includes the current HARRY function. It would be better if you can easily connect various services to centrally manage all machines (EX: DISCORD, LINE). I am willing to promote and pay a fee.

**Comment by abueide** [comment]
@a19901201 that is the plan. it'll have easy harvester setup & monitoring/notifications. allthough some of the more advanced harvesting features like notifications & stats might come after the initial 1.2 release
