### ISSUE TITLE
lost plot.tmp.2 after pressing stop

### ISSUE THREAD

**Issue by dbrah** [abueide/harry-plotter#103]
Hi again

I had a plot get stuck on the copy to final location step because the final location didnt have enough space. The tmp file appeared to be complete so I pressed stop in Harry Plotter intending to manually copy it to a different location and change the extension, however it looks like when I hit stop in Harry Plotter, it deleted the plot all together. I imagine this is part of a cleanup step so temp files arent left after stopping a plot mid-plot, but if it finished 4/4 it should leave the temp file. 

 Future feature would be cool if HP recognized a plot stuck at this step and ask you to enter a new location.

Cheers

**Comment by abueide** [comment]
yup you'd need to close with a graceful stop instead of a force stop which cleans up temp files
