### ISSUE TITLE
No statistics on parallel job

### ISSUE THREAD

**Issue by dbrah** [abueide/harry-plotter#104]
See attachment. Not seeing phase or last plot time for second running job. The job in the picture already completed a plot and is running it's second one, but no statistics for either are showing up. 
![image](https://user-images.githubusercontent.com/85514121/121218289-994f9300-c850-11eb-962b-ede30cdb1f95.png)

**Comment by konkersgg** [comment]
It will only display statistics when it creates the first plot on that job.
