### ISSUE TITLE
Absolutely impredectible behavior in 1.1.14

### ISSUE THREAD

**Issue by josemanuelhda** [abueide/harry-plotter#105]
I must say that I love the idea of your software, and I have made quite a bunch of plots, but not I cannot use it anymore, I am done, most of the times when I run it and say start stagger nothing happens, well, really it does not work for me any more, another times I close the program and open it again and it apparently starts with the stagger options saved (4,4,4 30 minutes, I use 4 diferent temp drives and the same for destination, that is the reason) nothing on temp drives configured or saved.

But when it starts staggering in the ocasions it decides to run this way, it always starts 2 different chia procesess at the same time and making 2 different plots, the program thinks it is making only one, but the 2 chia.ese are running at the same time in the same drive, I know this because I can see the different names of the temp files created in the drive.

So now I am totally stacked, I am thinking about using older versions or using chia client.

Is it possible that the new chia app 1.1.17 is causing this behavior?

I use this machine only for plotting, so the chia client is never running except comanded by hp, but I updated it yesterday I thing, and I don't know if this may be the problem.

I will try with hp 1.1.11 and update info.

**Comment by abueide** [comment]
Hi, sorry that you're having this experience. Please update to harry plotter 1.1.14 (it has a bunch of bug fixes since 1.1.11). You can update while plots are still running.

Also please read through the wiki, specifically the getting started section. It contains a lot of info about how to use the program so it will work like you expect it to. Especially read the testing with k25's section in the optimization guide, I think it will help you make sure your setup is working as expected.

https://github.com/abueide/harry-plotter/wiki/Getting-Started

https://github.com/abueide/harry-plotter/wiki/Optimization-Guide

If you've done this and its still not working feel free to stop by the discord and I'll help to figure out what issues you're having and try to resolve them in harry plotter. I'd really like to understand more about what's going wrong so I can fix it.

**Comment by josemanuelhda** [comment]
Hi, thank you so much for your atention, although 1.1.11 may be buggy, now I don't need low memory jobs so I can do my plotting with 1.1.11, it is working fine with chia 1.1.7, so no need to make more testing, as I have already lost half a day plotting time.

I have done tests on my system with k25 plots also, so no need to re run them.

I have uninstalled 1.1.14 and installed 1.1.11, my jobs were there, not erased by uninstall, and everything is working fine no, although with no low memory settings and no stats avalaible, but working as it should.

Previously I hade uninstalled and reinstalles 1.1.17, reset settings, erased everything and repair instalation too, tried everything, but with the bizarre behavior explained in my initial post. Everything double and triple checked.

No restart windows with the old version, so all enviromental variables were the same, I cannot find or explain what the problem was, I am sorry for that, as I understand people's concern about my report, but at least if somebody comes to the same place I arrived they can do what I have done and keep using your program, wich I really love, even with the bugs.

**Comment by abueide** [comment]
I'll try to do some more testing to see if I can make what you described happen locally. If I can get it to happen I'll be able to fix it. Thanks for the info again.

**Comment by josemanuelhda** [comment]
yes, 2 identical processes started at the same time running in windows task explorer, that is what happens

**Comment by abueide** [comment]
I can't make this happen. Is my setup different than yours in any significant way?

![image](https://user-images.githubusercontent.com/19354425/121257925-e2fda500-c873-11eb-8e3b-6167b87d633a.png)

**Comment by abueide** [comment]
here's another test using the same stagger settings on 2 separate drives
![image](https://user-images.githubusercontent.com/19354425/121258477-8fd82200-c874-11eb-8410-6ec5e5db6fd9.png)

**Comment by deljjar** [comment]
now i'm using 1.1.11 which ran with less problems and my plots ending at an average of 04h30m, I make 3 plots in parallel with stragger 30min.
I don't know if I can talk here or open another topic, it happened when I migrated to version 1.1.13 my plots started to take longer than normal, on average 6hrs.

**Comment by deljjar** [comment]
about duplicate jobs, it didn't happen very often.

**Comment by abueide** [comment]
@deljjar i believe the performance problem was a bug with stats which is now fixed in 1.1.14. but no need to upgrade if it's working until there is a feature you want.

**Comment by deljjar** [comment]
> here's another test using the same stagger settings across 2 separate drives

try to start a job, and cancel it, and try again that same job to see if what happened to us happens, this duplication.

**Comment by deljjar** [comment]
> @deljjar i believe the performance problem was a bug with stats which is now fixed in 1.1.14. but no need to upgrade if it's working until there is a feature you want.

I will do tests on 1.1.14 when I finish my work, I like news

**Comment by josemanuelhda** [comment]
> 
> 
> these are the stagger settings I used
> ![image](https://user-images.githubusercontent.com/19354425/121257974-f0b32a80-c873-11eb-8c4d-5bcdf76118d0.png)

my settings are very similar, 4 different drives, stagger 4 4 4 and 30 minutes, I try to make them work at the same time, one on each different, but similar drives, and final destination the same drive, it works perfect for me when hp obeys, but when I push start stagger nothing happens, I close hp and start it again, and some times it starts the stagger by itself but with duplicate proceses, this is as accurate as I can tell you how things work

my pc has 16 threads and 16 gig of ram, so I give every job 3 threads and 3 gigs or ram, so I leave for windows and other tasks 4 threads and 4 gigs of ram, I don't know it this adds some more information to you

I have only let this happen with the first plot, as my drive cannot hold more than one, when I notice 2 plots running I force stop from hp, it works with only one of the plots, If i kill in windows task any of the plots instead of asking hp it kills the process in hp too, no matter wich one I chose

both plottings start simultaneously but with different name in the plot, I can see that in the files in the temp drive

the most annoying thing is stagger all not working at all in my case, it only works when starting hp, it starts auto, not always, but with 2 proceses at the time

once I did not notice the double plotting and I restarted hp to realize I had 4 jobs running at the same time in the same drive (I had not killed the first 2)

I use chia plot status to monitor plotting, and it detects instantly this behavior

I am sorry you cannot duplicate the problem, but it is there, stagger all does not work at all, but in the same windows session with 1.1.11 everything runs as it should, no restart in between as I already told you, and no duplicate plotting

**Comment by abueide** [comment]
wait so you're saying the duplicating only happens when you restart harry plotter?

**Comment by josemanuelhda** [comment]
I am thinking, as I use static time in stagger, and you  have added another option in 1.1.14 that was not in 1.1.1.11 that maybe the time variable is located in the wrong place in the code, you could try the same settings I quoted with 1 minute or 2 static time to see it this make the program go nuts, I use 30 minutes, if that is the issue you don't have to wait for the second plotting, as the duplication is at the first plot already

**Comment by josemanuelhda** [comment]
> 
> 
> wait so you're saying the duplicating only happens when you restart harry plotter?

yes, because start stagger stopped working, I used it for a couple of days normally, but then it went this way, no reinstalling or reseting settings could solve it

**Comment by abueide** [comment]
okay thats really useful info thank you

**Comment by josemanuelhda** [comment]
I have sent you an email with my telegram address in case I may help you chatting

thank you so much for your work

**Comment by firipusan** [comment]
Sometimes on 1.1.14 when you restart duplicates start which uses more cpu and ram than normal. I just restart the pc and reopen harry plotter until this does not occur then everything works exactly like it should. This did not happen on 1.1.11 but we did not have drive control.

**Comment by MinesofMoriaCrypto** [comment]
I think this is probably related to the issue that I'm having too. It seems that it prioritizes certain limit settings, and if it satisfies the one, it stops paying attention t some of the others.

**Comment by flutech82** [comment]
I previously posted a SPEED ISSUE ,now I have same problem from when I installed version with DRIVES TAB 1.1.14.
I checked on 500 gb NVME and have ERROR 1 problem (disk full) when plotting because it started more than 2 plots.
Here below my configuration, maybe I made some mistake.
![image](https://user-images.githubusercontent.com/84220972/121774246-d3d36b80-cb81-11eb-95bf-7a548d8a5eeb.png)
![image](https://user-images.githubusercontent.com/84220972/121774254-e352b480-cb81-11eb-8f6e-ad2222add65c.png)
![image](https://user-images.githubusercontent.com/84220972/121774260-eea5e000-cb81-11eb-9e1a-e65810cc943d.png)

**Comment by flutech82** [comment]
FOUND SOMETHING!!!!
I removed stagger configuration SETTINGS
I tryed to START STAGGER and nothing happen, so I push another time START STAGGER and nothing happen.
I closed HARRY PLOTTER and reopened, in this way I see nvme2 and nvme 1Tb 1 JOBS running...BUT SURPRISE!!!......in temp folders I found 2 plots running for each JOB, it means each time I push START STAGGER I start a Plot series,I thought there must be 30 minutes configuration blocking new starts.

**Comment by josemanuelhda** [comment]
I keep on using version 11 until this is solved

**Comment by abueide** [comment]
let me know if you guys are still having issues in 1.2.0
