### ISSUE TITLE
User interface goes blank

### ISSUE THREAD

**Issue by Strider3099** [abueide/harry-plotter#107]
This happened on 1.1.14 on Windows 10. 

I'm not sure how to replicate this issue, it happened as I was resizing the window while the plotting jobs were running. 
I thought it was due to high CPU and memory usage but when my plotting tasks  were done, it didn't reappear.

Screenshot: 
<img width="767" alt="Screenshot 2021-06-14 at 12 50 29 PM" src="https://user-images.githubusercontent.com/85860408/121840690-5178b200-cd0f-11eb-8347-17c5329944c8.png">

**Comment by abueide** [comment]
Hi,

This is a bug in javafx where if the rendering pipeline is broken (after updating your graphics driver, using remote desktop, etc) then the rendering pipeline isn't rebuilt. To fix this click x twice in a row and reopen harry plotter. it should reconnect to the plots. If it is a consistent problem use the software rendering 1.1.14-RC build which should stop it from happening.
