### ISSUE TITLE
Feature request: report total plots in last 24 hours

### ISSUE THREAD

**Issue by luotinen** [abueide/harry-plotter#108]
I have more than one concurrent jobs. Would it be possible to display somewhere the total statistics of all jobs. In particular:
- Average Plot Time (of all jobs)
- Total Plots Create (of all jobs)
- Estimated Plots Per Day (of all jobs)
- Plots in the last 24 hours (of all jobs)

**Comment by abueide** [comment]
this is already implemented in 1.1.14 under the stats tab
