### ISSUE TITLE
Bug? All jobs report "Stopped"

### ISSUE THREAD

**Issue by luotinen** [abueide/harry-plotter#109]
All of my jobs report "Current Status = Stopped" but I know they aren't as I can see the % changing normally and more plot files appearing. I was able to force them to report the correct stage by pressing "Start All" button after which the Current Status is working normally again. The problem appeared after quite a while of plotting.

**Comment by abueide** [comment]
try using 1.1.14

**Comment by abueide** [comment]
let me know if this is still an issue in 1.2.0
