### ISSUE TITLE
Feature request: Graceful stop

### ISSUE THREAD

**Issue by luotinen** [abueide/harry-plotter#112]
Currently, if the user hits (hard) stop all, then all plots are stopped and the progress is lost.

I suggest a feature, graceful stop, which would let plots run their course but do not proceed to the next plot but stop instead upon completion.

It could be implemented with the drag-down option to the Stop All button as an option to Gracefully Stop All.

**Comment by abueide** [comment]
This is already implemented. Just click stop all and it will ask you if you want to force stop or graceful stop.
