### ISSUE TITLE
Satatus stay to 0% and it is plotting 

### ISSUE THREAD

**Issue by jess4140** [abueide/harry-plotter#13]
Plot size is: 32
Buffer size is: 10000MiB
Using 128 buckets
Using 4 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Thu May 20 19:44:42 2021
Computing table 1

NOTHING HAPPEN AFTER THIS

**Comment by abueide** [comment]
Yeah this one is weird. I started getting this after updating to 1.1.5 (i was still on 1.1.3 for my plotting machine, but I updated after some other people were reporting issues). I'll look into it, sorry about that!

**Comment by abueide** [comment]
I think I found the problem, will give it a test and push out an update shortly.

**Comment by abueide** [comment]
@jess4140 let me know if 1.1.3 release works ok for you

**Comment by jess4140** [comment]
Nope problem still the same on my end
