### ISSUE TITLE
issu with make new plot

### ISSUE THREAD

**Issue by jess4140** [abueide/harry-plotter#15]
put setting to make new plot,save it 
after just changing name of the new plot ,will not save it

**Comment by abueide** [comment]
after you changed the name did you click the save button? if you did can you try restarting after changing name and clicking save? did you use the right click duplicate feature at all?

**Comment by luotinen** [comment]
Please add a button "Add job".

The current way of having to duplicate one by right-clicking it first is cumbersome and not intuitive.

**Comment by abueide** [comment]
@luotinen in 1.1.5 you can click cancel and then fill out a new job and click save

**Comment by luotinen** [comment]
I tested it and it works.

The current process is:
Step 1: Fill in the job details
Step 2: Press "Save" to "Save"
Step 3: Press "Cancel" for "Add new job"

The suggested process is:
Step 1: Fill in the job details
Step 2: Press "Save" to "Save"
Step 3: Press "New" for "Add new job"
