### ISSUE TITLE
Jobs panel does not update when a staggered job is started.

### ISSUE THREAD

**Issue by DilatoryCheetah** [abueide/harry-plotter#22]
Version: 1.13-Beta

Steps:
1. Configure multiple jobs
2. Set a positive number in the "Minute Stagger" field
3. Click on the "Start All" button
4. Wait for x+1 minutes as specified in step 2.

Result:
The second job in the Jobs panel does not get updated to show "- 0.0%" indicating that the job has started

Expected:
Every job should automatically update when it starts or changes phase

Note:
Clicking on the second job will update the Jobs panel showing that it is started

**Comment by abueide** [comment]
currently estimated percentages aren't implemented yet, but i'll be sure to fixe this when I do implement them.

**Comment by abueide** [comment]
fixed in 1.1.5
