### ISSUE TITLE
No jobs get added after save

### ISSUE THREAD

**Issue by cojarbi** [abueide/harry-plotter#27]
Created Job1, saved and started
Created Job2, click save nothing happens

Restarted the app Job1 disappears and Job2 is there

**Comment by abueide** [comment]
Hi. I think there might be a bug with saving new jobs right now (what happens after clicking the cancel button).

For a temporary workaround have you tried right clicking the job and clicking duplicate & editing the settings?

**Comment by abueide** [comment]
let me know if you're still having issues on 1.1.5

**Comment by cojarbi** [comment]
Ill review 1.1.5 shortly, thanks

**Comment by cojarbi** [comment]
Adding, duplicating jobs seems to work. Im getting a -?% next to the jobs when i start it. Also, the Stats screen is unpopulated.

Are you using the chia.exe to run this plots? Im using an app called chia plot status that feeds from a log folder but im not getting anything when i start a job here.
