### ISSUE TITLE
Maximum Plots in Phase 1 limit does not work

### ISSUE THREAD

**Issue by luotinen** [abueide/harry-plotter#31]
To reproduce:
- set Maximum Plots in Phase 1 to "1"
- create a job and start it
- create another job and start it
=> Two plots are now in Phase 1 despite the restriction to have a maximum of 1 plots in Phase 1

**Comment by abueide** [comment]
the stagger settings only apply when you click the "start all" button.

if you manually start a bunch of plots its not going to stop you from doing so.

**Comment by luotinen** [comment]
Do you mean that a text should be added "Stagger Setting only apply when the Start All button is used" to the Stagger Setting screen?

**Comment by abueide** [comment]
Sure I'll do that. Thanks for the suggestion!

**Comment by cojarbi** [comment]
So i guess the idea is create/duplicate a bunch of jobs and then Start them all?

If this is the case, when is the "Stop After" applied? Is it going to loop for X after each one finishes?

**Comment by abueide** [comment]
@cojarbi when you click start/start all it starts a counter for that specific job that counts how many plots its completed. once it reaches that number, it will stop making new plots until you start it again at which point it will reset the counter.

let me know if you still have questions

**Comment by cojarbi** [comment]
Its fine just trying to wrap my head around the logic. its a superb solution ( and i have used Plotman and Sawr )
