### ISSUE TITLE
Progress percentages cannot be seen, instead "?%" is displayed

### ISSUE THREAD

**Issue by luotinen** [abueide/harry-plotter#32]
To reproduce: create some jobs and start them with the Start All button.

I named my jobs:
First
Second
Third
Fourth

The progress is being reported like this:
First - ?%
Second - ?%
Third
Fourth

However, if I click the jobs, I see that the actual progress is:
First - Running phase 3/4
Second - Running phase 1/4
Third - (due to my rules waiting for phase 1 begin)
Fourth - (due to my rules waiting for phase 1 begin)

**Comment by abueide** [comment]
the ? means that it doesn't have any data from previous runs to be able to calculate what the average time to complete the plot is. Once it finishes a plot then you'll see the percentage estimations

**Comment by luotinen** [comment]
Now I am seeing:
First - 0.84%
Second - 0.40%
Third - 0.03%
Fourth - (due to my rules waiting for phase 1 begin)

Does it mean:
First - 84 %
Second - 40 %
Third - 3 %
Fourth - (due to my rules waiting for phase 1 begin)

The actual progress is:
First - Phase 3/4
Second - Phase 2/4
Third - Phase 1/4
Fourth - (due to my rules waiting for phase 1 begin)

=> Can you fix the decimal error and also add the phase information to the job list?

**Comment by abueide** [comment]
yeah I completely forgot to multiply by 100 to make it a percentage, will do that.

I'll go ahead and do that

**Comment by abueide** [comment]
fixed in 1.1.6

**Comment by 350d** [comment]
@abueide I guess we can do better job here since all phases logged and we talking about %, not about exact time in seconds (but still we have exact seconds after every phase finished), so, starting phase 1 means 0%, copy finished - 100%, phase 2 ~ 25%, etc, each phase can be divided by sub-phases, like plotter need to compute 7 tables in phase 1, so, 25/7 ~= 3.5% per table.

**Comment by abueide** [comment]
@350d this is the plan, there's just other more important things that I'd like to get finished especially before pooling comes out than adding the parsing necessary to do this. of course you can always feel free to leave a tip to help prioritize it.
