### ISSUE TITLE
Preventing more plots from being generated

### ISSUE THREAD

**Issue by cojarbi** [abueide/harry-plotter#39]
What's the procedure to stops plot jobs after the current one is finished?

**Comment by abueide** [comment]
hi, currently the procedure is to either
1) go through all of your plots and set the "Stop after" setting to 1
2) click the x button on harry plotter and choose "let them finish" on the popup (this won't save stats, and you won't be able to see the plots' status anymore.

In the next release I'll add a "Graceful Stop" button

**Comment by cojarbi** [comment]
@abueide making the change to 1 and saving does not seem to work on 1.1.5. Neither stoping them manually. Some keep respawning.

**Comment by abueide** [comment]
ah there might be a bug when using the stagger scheduler (the start all button). i'll look into it more
