### ISSUE TITLE
Stop after X Plots doesnt work

### ISSUE THREAD

**Issue by CDprotector** [abueide/harry-plotter#43]
I made 5 different jobs, set Stop after 2 Plots for every job, Saved , Started All and it just keeps going forever, no stop in any job. Need to manualy Stop All jobs.

Will be happy if Logging will be added and phase stage and times counted.

BTW, nice utility, keep up productive work, I appreciate it.

**Comment by abueide** [comment]
fixed in 1.1.7

**Comment by cojarbi** [comment]
I created 4 plots to run overnight, all of them were setup to stop after 1 , i just had 1 respawn after finish.

Is the stop after one means that 1 is going to get done or 2?

V1.1.6
