### ISSUE TITLE
Keys cannot be manually added

### ISSUE THREAD

**Issue by pshepperd26** [abueide/harry-plotter#46]
Clicking "add" to add farmer and pool key does nothing unfortunately. No window, no pop up.

System is a clean install of chia, but with no default wallet present on the system.

**Comment by pshepperd26** [comment]
It is working in 1.1.6.... and I see you just released 1.1.8 so I will try that now.

**Comment by abueide** [comment]
yeah sorry about that i made a typo that cause it to not be able to load the key editor
