### ISSUE TITLE
the start all button is not working

### ISSUE THREAD

**Issue by deljjar** [abueide/harry-plotter#47]
the start all button is not working. in version 1.1.7

**Comment by abueide** [comment]
could you tell me what platform you're running on?

**Comment by deljjar** [comment]
windows 10 64bits. in the previous version it was normal

**Comment by abueide** [comment]
weird on my development machine it works but on my testing machine it doesn't.

I'm just going to delete the releases for now till I get this figured out.

**Comment by deljjar** [comment]
I passed this version on to my friend, he also reported the same problem with the button does not start all

**Comment by abueide** [comment]
I will start making liberal use of the "pre-release" feature from now on so these types of bugs don't happen in stable builds anymore. Sorry for the troubles.

**Comment by deljjar** [comment]
no problem, the application is getting very good

**Comment by jmz-bit** [comment]
Same problem here with start all button is not working version 1.1.8

I'm back to 1.1.6 and is OK

It is a great app. Thank you for hard work. But I think that the releases are published too quickly.

**Comment by abueide** [comment]
@jmz-bit yeah I'm going to slow down on the releases and start to do pre-releases signifying that they might be buggy. I'll work really hard to make sure that the green non-prereleases are stable from now on.

**Comment by jmz-bit** [comment]
> @jmz-bit yeah I'm going to slow down on the releases and start to do pre-releases signifying that they might be buggy. I'll work really hard to make sure that the green non-prereleases are stable from now on.

I think that this is a good idea. 

My problems with 1.1.8 is also my fault as I didn't read other comments. Just jumped from 1.1.6 to 1.1.8 without thinking ;-)

You are already doing great work here. This app is what lots of people was looking for. Simply but smart plotter with GUI.
