### ISSUE TITLE
Feature Request: Graceful Stop

### ISSUE THREAD

**Issue by Mojo-LB** [abueide/harry-plotter#51]
Hi, 

I've been watching your work and I'm impressed by your dedication. I will donate once I start generating Chia, but now all my extra funds are locked in hardware.

I know you are currently busy with all the latest releases, but wondering if you can find the time  to add a Graceful Stop option.

Idea is when I have plots running using Start all button,  I would want to stop to upgrade my machine or update your software or Chia, without losing current progress.

So a Graceful Stop would stop spawning new jobs but waits for running jobs to complete, whereas Stop All terminates everything

**Comment by abueide** [comment]
done in 1.1.7
