### ISSUE TITLE
Jobs per temp device

### ISSUE THREAD

**Issue by firipusan** [abueide/harry-plotter#55]
Hi

I could be wrong here but have you considered jobs per ssd/nvme then control staggers etc per ssd/nvme individually and then a global setting with max so you can limit according to cpu and ram etc?

Also are you able to put a secondary temp directory underneath the temp directory line?

transaction id:6S7457274J915242U

thanks!
Phil

**Comment by firipusan** [comment]
Hi Andrew

The next update sounds great.

Just wanting to be able to have for eg first 3 staggered 30-90min to have them in phase 1. That drive would have setting of max 3 in phase 1, and 4 in phase 2-4. but the plots after the first three ca start after any of the initial 3 come out of phase 1, for a total of 7 plots at any given time. 

Are you also able to show number of plots stored currently per destination drive and limit the transfer to this drive if full?

Would also be great to be able to auto transfer plots from plotter to harvester etc so that I can leave the plotting on auto. I have no idea about the difficulty of actually achieving any of this..... so ignore if unachievable.


Thanks!
Phil

**Comment by abueide** [comment]
Oh so you would like a setting to be able to set the maximum plots on a single drive in addition to the other stagger options if I'm understanding correctly. Sure, I can do that.

As for transferring plots from the plotter to the harvester, the caching mechanism in the next update will be really useful for that. You'll be able to define a network destination drive to send it over the network (its going to be prettly slow unless you have a 10 gbps connection to your other machine).

**Comment by firipusan** [comment]
Hi Andrew

Wanting to stagger just the intial 3/7 plots 90min apart so 3 in phase 1, then the 4/7 can start as soon as the 3/7 plots come out of phase 1. The reason I want to be able to stagger just the first 3, is because the times change according to hardware limitations and differences.

The network functionality sounds amazing! So that would mean that it would auto fill hdd/s and switch to the next hdd/s once full?

thanks!
Phil

**Comment by abueide** [comment]
Ohhh okay I see. I think I understand better now. I'll try to keep that use case in mind while I'm working on the caching feature.

The initial version will probably require you to set up your own network solution (e.g. mounting network drives so my program can interact with them as if they're just a folder on your computer), but in the future I can look at integrating some sort of built in networking solution using rsync or something else. Essentially yeah it would fill up the next drive after one is full and automatically distribute your plots in such a way to maximize your IO lanes whether its an internet connection or between drives on the same system.

**Comment by firipusan** [comment]
Hi Andrew

Thanks mate! Looking forward to the new update.


Phil

**Comment by Unpacking** [comment]
I am also interested in using 2 different configurations on 2 different NVMe. 

Thank you very much for your work.

**Comment by firipusan** [comment]
Hi

Can you add stagger settings per drive, same as the global setting whilst we are waiting for the big update.

**Comment by abueide** [comment]
@firipusan I'll try to get a basic version in for the 1.1.12 release which should be tomorrow or the day after. This release will also have the stats tab implemented, and several bugfixes.

**Comment by abueide** [comment]
done in 1.1.12
