### ISSUE TITLE
Start next plot after PH1

### ISSUE THREAD

**Issue by RoySmits** [abueide/harry-plotter#65]
I have been using Programkoms Chia PlotManager and they have an option for delay between plots to be set at "after phase 1"
Where when you start a batch, the next plot will start after the previous plot has finished phase 1.

Could you please implement this?
Their manager creates a new folder for every plot, which is a disadvantage because of the final plot.2.temp rewrite issue.
I like that HP just puts all plots in the same temp file and just renames the plot in the final file.
But HP only starts a new plot after the previous is finished.
If I want to stagger plots, I still have to do this manually, which is quite a hassle considering I can't watch the system 24/7.
![PlotManager](https://user-images.githubusercontent.com/33250998/120051996-6244da80-c023-11eb-804c-4ed18ae103b0.PNG)

**Comment by abueide** [comment]
hi this is already implemented. go to settings -> stagger settings and set "maximum plots in phase 1" to 1, and then it will start each plot after the last one goes to phase 2

**Comment by RoySmits** [comment]
I did have that selected.
Maybe if the app showed the progress of every plot seperately it would be easier to see.
Something the above mentioned manager has as well, they show a % of completion per plot instead of the cli output.
For now it seems as if it just runs 1 plot a time as far as I can tell according to the screenshot it finished phase 4, and only then started a new plot.
I will keep a closer look on it today.

![Knipsel](https://user-images.githubusercontent.com/33250998/120064564-1c146900-c06d-11eb-8aa4-0233cd657037.PNG)

**Comment by abueide** [comment]
you can also test out using k=25 and "--override-k" in the extra args field so you don't have to wait so long to test if your settings are working properly. also send a screenshot of your stagger settings & what version you're on and I might be able to help a bit more

**Comment by RoySmits** [comment]
Seems like it was my mistake, I have multiple machines, and this one I forgot to set the stagger settings.
Sorry mate.
Working like a charm. 😅
