### ISSUE TITLE
Autostart on system reboot

### ISSUE THREAD

**Issue by SauravKumal** [abueide/harry-plotter#67]
would it be possible to have an option to set for auto start at system reboot and run plots after cleaning temp drives?

**Comment by abueide** [comment]
hi in version 1.1.12 if you shut down using a graceful stop (or if it gets force killed) it'll automatically start the stagger manager & clean temp dirs of all of your jobs. if you can find a way to autostart harry plotter, then you should be able to achieve this. let me know if it works

**Comment by KD7LRJ** [comment]
This should work to get Harry Plotter to autostart when you login to Windows 10:

1. Hit Windows+R (run)
2. Enter "shell:startup"
3. Click "New item" in the toolbar (or Right click in open area on the right and choose New).
4. Browse to the location of the Harry Plotter executable and hit enter. For me it's in: "C:\Users\Doug\AppData\Local\Harry Plotter\Harry Plotter.exe". (Change the user directory name if you cut/paste my entry :)
5. Name the shortcut. "Harry Plotter" seemed reasonable to me.
6. Click "Finish"

I haven't tried it yet (don't want to interrupt plots as long as things are working well), but I just added it and I'll find out the next time I need to reboot that machine. I have a similar entry for the Chia executable (C:\Users\Doug\AppData\Local\chia-blockchain\Chia.exe) on my Farming machine that has been working fine for a while now.

**Comment by SauravKumal** [comment]
> hi in version 1.1.12 if you shut down using a graceful stop (or if it gets force killed) it'll automatically start the stagger manager & clean temp dirs of all of your jobs. if you can find a way to autostart harry plotter (using a system script or service which is platform dependent), then you should be able to achieve this. let me know if it works

ok. in version 1.1.12 starting harry-plotter with crontab at reboot does the job. Thanks!
