### ISSUE TITLE
Error - Unsupported JavaFX configuration

### ISSUE THREAD

**Issue by kristi1974** [abueide/harry-plotter#70]
When i start 1.1.9 i have this error:
May 30, 2021 4:37:46 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3ce6a158'

**Comment by jmz-bit** [comment]
I have this same problem. Terminal window with this same message. But program is working OK so far. But if I will close this terminal window the app will turn off itself.

**Comment by abueide** [comment]
hi guys this is just a warning due to me not using java's module system. its completely normal. I just turned on logging for this release so people can report issues easier. If people don't like the console window I can turn it off again.

**Comment by jmz-bit** [comment]
> hi guys this is just a warning due to me not using java's module system. its completely normal. I just turned on logging for this release so people can report issues easier. If people don't like the console window I can turn it off again.

Thank you for the information. So this extra window could help provide more detailed informations in case of problems. No problem with that. But maybe you could add extra button/switch to turn it on or off.

One more time, thank you for your hard work. I can see that you are spending a lot of time on this project.

**Comment by abueide** [comment]
due to the way the console works (it runs the application from the console, therefore the console is attached to the application's process so when you close it so does the application).

Because of this I can't make an option to toggle it, I can only decide to make a build with it on or make a build with it off. In future releases I'll make my own logging system which will log to a file instead and display a popup when warnings/errors occur so you can report it easily. For now I just thought this would be easier.

**Comment by jmz-bit** [comment]
OK. Thank you for the informations.

If this will help make this app better... no problem with this extra window. It was just making me confusing at the beginning.

PS.
I just noticed that a new version is avaiable. Is it possible to do upgrade without canceling current plots in progress?

**Comment by abueide** [comment]
yes, just make sure to click the graceful stop option after you click the red x on harry plotter. you only need to upgrade if you want to turn off the logging window (since thats the only change)

**Comment by kristi1974** [comment]
Thank you for the information, i`ll stick wit 1.19, it`s good to see the logging info.
