### ISSUE TITLE
Plot does not end.

### ISSUE THREAD

**Issue by Unpacking** [abueide/harry-plotter#73]
The plots finish, they are copied to the final disk, but they don't finish. The% keeps increasing and counts as an asset. I must delete the finished file "stopped", so that the "stagger" works correctly. All finished plots keep counting and increasing their% ... 120% 200% 500% ... in "stopped" status.

System - Ubuntu - Last version. 20.04?
![error ploteo](https://user-images.githubusercontent.com/84914341/120122054-cf34ad80-c1a6-11eb-9143-ba5b938f2255.JPG)

**Comment by abueide** [comment]
what harry plotter version are you running?

**Comment by Unpacking** [comment]
1.1.8-1

i'm go to try with 1.1.11-1

**Comment by abueide** [comment]
let me know if you're still having issues on 1.1.12
