### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Khunmatthew** [abueide/harry-plotter#78]
Hello there! Is it possible to post a tutorial video about the use of the program? Some places are not used very clearly.

**Comment by abueide** [comment]
yup I'm working on a text tutorial outlining all the features and how to use them. I'll use this as the basis for making a video tutorial. Not sure when it'll be done, but I'll start on it after the 1.1.12 release today or tomorrow.

**Comment by abueide** [comment]
you can check out the new wiki here https://github.com/abueide/harry-plotter/wiki
