### ISSUE TITLE
Limiting the number of parallel processes on the hard disk.

### ISSUE THREAD

**Issue by figaro001** [abueide/harry-plotter#79]
Currently, there is a limitation on the number of parallel processes (for example, for phase 1) per system. This is useful if I have one large and fast plotting disc. But if I have a lot of plotting disks? I would like, that on one disk there were no parallel tasks for plotting working in phase 1. Can this be implemented?

**Comment by abueide** [comment]
if I'm understanding correctly you want stagger settings per drive? if this is the case I should have a  solution out for the 1.1.12 release tomorrow or the day after.

**Comment by figaro001** [comment]
Yes, I want the settings for each drive to be different. Thank you!

**Comment by abueide** [comment]
done in 1.1.12
