### ISSUE TITLE
black window

### ISSUE THREAD

**Issue by SilantevDenis** [abueide/harry-plotter#80]
![black](https://user-images.githubusercontent.com/18242419/120386328-2bc3d400-c331-11eb-977d-6243dc60d01d.jpg)

**Comment by abueide** [comment]
is this when using remote desktop software? if so which remote desktop are you using, and which version of harry plotter are you using?

**Comment by abueide** [comment]
@SilantevDenis so I can't reproduce this. here's a few things to try: you can exit harry plotter and reopen it while plots are still running. just click x on the big window and when it asks you are you sure just press x again and it defaults to a graceful stop. then you should be able to open harry plotter again and it should detect the plots that are still running. 

Also make sure you are on the latest version. You can check by going to help -> about. If it happens again let me know and I'll try to do some more testing.

**Comment by abueide** [comment]
let me know if this is still an issue for you and I'll reopen
