### ISSUE TITLE
memory assigned for plot does not work if under 3000 megabytes per plot

### ISSUE THREAD

**Issue by josemanuelhda** [abueide/harry-plotter#81]
when I assign low memory for plotting (minimum official is 900 megabytes) it keeps giving each plot the default quantity of 3389, it works with 3200 but  not with 3000, 2800 2500 2200 1800 or 1500 that I have tried, it is an annoying bug for low memory systems

**Comment by josemanuelhda** [comment]
I have read other issues trying to assign more memory also, so I guess this problem is similar to the other one, hope you are working on it

**Comment by abueide** [comment]
oh I have the threshold minimum at 2500 MiB because I saw that number in this blog post which appears to have been updated recently

https://www.chia.net/2021/02/22/plotting-basics.html

I will fix this for 1.1.12 which is coming out today

**Comment by josemanuelhda** [comment]
great, thank you, I think 900 megabytes is the minimum, maybe 1 gigabyte to avoid surprises

thank you so much

**Comment by josemanuelhda** [comment]
and in case it is easy to implement and you consider it, I will explain my situation, that may be also useful por other users

I hace 2 disks that run fast, but I have also others than are quite slower, what I would like si to make 2 different jobs, one for the quick ones and one for the slow ones, and the conditions should be different for both jobs in terms of staggering

i can open 2 different instances of harry plotter, but I don't know if they will interfere one with the other

**Comment by abueide** [comment]
fixed in 1.1.12
