### ISSUE TITLE
Stagger not working 1.1.12

### ISSUE THREAD

**Issue by firipusan** [abueide/harry-plotter#84]
Hi Andrew

Appreciate the drive stagger settings on the new release! 

Setup of stagger per drive on 1.1.12 is excellent, not too much deviation from what was existing from global stagger settings. I do wonder if the jobs tab is now redundant?

I setup stagger settings for 8 plotting drives, 2 plots in phase 1 and 3 plots in phases 2-4 with 90min stagger time, max 5 plots per drive. Then set global stagger settings for 16 in phase 1, 24 in phases 2-4 with no static stagger time. Started, was going great but did not start the fifth set of plots and has only 1 set in phase 1.

**Comment by abueide** [comment]
yeah the stagger doesn't work unless you add a drive in the drives tab. this will be fixed in 1.1.12-RC2

**Comment by firipusan** [comment]
Previously when the programme gets laggy, I close and reopen which would maintain the current plots and get rid of the lag. With 1.1.12 reopening starts the next 8 plots.

Also more cpu seems to be getting used but with a slower plot time.

**Comment by trs-80** [comment]
I am experiencing the issue as well where I can no longer use "Start Stagger"

For some reason on Mac it seemed to work fine, but on Windows it is not. I will need to recheck on the mac once my current plots finish to verify my claim.

**Comment by abueide** [comment]
is this still happening on 1.1.14? did you guys figure it out? sorry for the late reply

**Comment by trs-80** [comment]
I will need to do some testing, but the auto starting on opening is happening in 1.1.14 which is not what I expect.

What does the test framework look like for this? There seem to be more and more combinations to contend with and wondering how I can accurately test to verify it is happening and if so under what conditions. Drive rules / stagger rules / etc.

**Comment by abueide** [comment]
@trs-80 you can use k25's to verify your set up is working how you expect it to. each one takes a few minutes to complete so you can see exactly how it works.

there's some useful info on how to do this in the wiki. but basically just use --override-k in the extra args box

https://github.com/abueide/harry-plotter/wiki

**Comment by trs-80** [comment]
I tested on Windows 10 and version 1.1.14 with two jobs and 'start stagger' worked as expected. The only option I have configured is the delay before the second job starts. I believe the time I had an issue was when I was experimenting with the drive stagger. I unfortunately don't have time to test that right now.

**Comment by abueide** [comment]
allright, thanks for testing. let me know if its still a problem in the future and I'll reopen.
