### ISSUE TITLE
1300 MB memory assignmet does not work either in 1.1.12

### ISSUE THREAD

**Issue by josemanuelhda** [abueide/harry-plotter#87]
Tried the new version with my low memory requirements and it still gives the recomended 3390 size ...

Also the program starts 2 jobs at the same time in the same disk even configured and started from stagger.

Turned back to version 1.1.11 and doing my low memory jobs with the official client, as your software cannot handle them ....

**Comment by abueide** [comment]
my bad I completely forgot to change the threshold. its fixed in 1.1.13
