### ISSUE TITLE
report for harry-plotter

### ISSUE THREAD

**Issue by lacho77** [abueide/harry-plotter#89]
Hello. I have been using the program for several days. It is very easy and excellent to work with. Everything is done with ease. Very, very good software. I want to ask, in the settings, although I set "Stop after" - 10 plots. It always stops after the second ready. Then I have to press "Start" again. I also can't save settings in Stagger. Why does this happen, where is my mistake? Thanks for your time.

**Comment by abueide** [comment]
Hi, what version of harry plotter are you using? Can you share some screenshots of your settings? What platform are you running on?

**Comment by lacho77** [comment]
Hello. I use a version 1.1.12.
![Screenshot_1](https://user-images.githubusercontent.com/85380429/120879160-1917fc00-c5ca-11eb-9808-5ecd72ec6b31.jpg)

**Comment by abueide** [comment]
so when you go to settings -> stagger settings and fill it out and click save it doesn't save?

**Comment by lacho77** [comment]
Yes my steps are: check stop after ... safe and start. And once 2 plots are ready, the process stops. I did it again and will try. Maybe I made a mistake before or something I didn't do right.

**Comment by abueide** [comment]
Its very possible its a bug, I'm doing some more testing now.

**Comment by lacho77** [comment]
[log-52deac9549471453599c6bf086d5f8be820bfd057a76fd0ccf7076ec3e7b324b.log](https://github.com/abueide/harry-plotter/files/6601993/log-52deac9549471453599c6bf086d5f8be820bfd057a76fd0ccf7076ec3e7b324b.log)

**Comment by abueide** [comment]
okay I'm able to get the same issue as you. I'll fix it in the 1.1.14 release. Thanks for the report!

**Comment by lacho77** [comment]
Thanks for your time. I will test.

**Comment by abueide** [comment]
fixed in 1.1.14
