### ISSUE TITLE
1.1.14 - High CPU 20% usage with doing nothing - after start

### ISSUE THREAD

**Issue by CDprotector** [abueide/harry-plotter#92]
I just start Harry Plotter and it takes 15-20% CPU utilization, not running jobs.

**Comment by abueide** [comment]
hi what version?

**Comment by konkersgg** [comment]
> I just start Harry Plotter and it takes 15-20% CPU utilization, not running jobs.

i was having the same issue. turns out it was due to corrupted log files. since i've removed them all, no more issues like that. (it's supposed to be fixed, but who knows). check that!

**Comment by abueide** [comment]
okay cool that's really useful to know, thanks for sharing.

**Comment by abueide** [comment]
let me know if this still happens in 1.1.14 i'll reopen
