### ISSUE TITLE
1.1.14 - GUI die after 12 parallel plots started

### ISSUE THREAD

**Issue by AcidBurnSB** [abueide/harry-plotter#94]
Plotting working, but GUI stuck and not show any think, same problem with 1.1.12
Windows 2008 R2 SP1

in PowerShell all working fine.

![Harry](https://user-images.githubusercontent.com/85442289/120924899-119a4500-c6e7-11eb-92e7-18084f6a4edc.jpg)

and after close Harry Plotter open them again GUI working... and plotting working...
![harry1](https://user-images.githubusercontent.com/85442289/120925368-6212a200-c6e9-11eb-91a1-ff431d4cd9a9.jpg)

**Comment by abueide** [comment]
try using the 1.1.14-RC build and let me know if you still have issues

https://github.com/abueide/harry-plotter/releases/tag/1.1.14-RC

**Comment by AcidBurnSB** [comment]
i use 1.1.14 same problem...

**Comment by abueide** [comment]
@AcidBurnSB there is 2 different 1.1.14 builds. one of them turns on software rendering to fix a blank screen issue. make sure you're using the version i linked.

**Comment by AcidBurnSB** [comment]
oh ok, i will try tomorrow, where plotting will finish, Thanks

**Comment by abueide** [comment]
@AcidBurnSB by the way you can update while plots are running
